spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG

jwt:
  secret: your-jwt-secret-key-that-is-at-least-32-characters-long
  expiration-ms: 86400000 # 24 hours

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}
  redirect:
    uri: http://localhost:8080/api/auth/callback
